FROM nginx:1.25.3

# Установка Certbot и плагинов
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx python3-certbot-dns-cloudflare && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/letsencrypt/live/zaiavka.xyz

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443