FROM node:22-alpine AS build

WORKDIR /usr/dictionary-server

COPY package*.json ./
RUN npm ci

COPY ./ ./
RUN npm run build


FROM node:22-alpine AS runtime

ENV NODE_ENV=production
WORKDIR /usr/dictionary-server

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /usr/dictionary-server/dist ./dist
COPY --from=build /usr/dictionary-server/drizzle ./drizzle

USER node
EXPOSE 4300

CMD ["node", "dist/main"]
